# -*- coding: utf-8 -*-
"""Streamlit Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/130Y6Ly_5MIN9fV1oc27XcsRqp6bBWtjt
"""

!pip install lightning transformers

!pip install pytorch-lightning==1.2.2

from google.colab import drive
drive.mount('/content/drive')

import lightning as pl
from transformers import AdamW, T5ForConditionalGeneration, T5TokenizerFast as T5Tokenizer
import pickle
MODEL_NAME = "t5-base"
tokenizer = T5Tokenizer.from_pretrained(MODEL_NAME,model_max_length=512)

model = pickle.load(open('/content/drive/MyDrive/t5.pkl', 'rb'))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile get_output.py
# import lightning as pl
# from transformers import AdamW, T5ForConditionalGeneration, T5TokenizerFast as T5Tokenizer
# import pickle
# MODEL_NAME = "t5-base"
# tokenizer = T5Tokenizer.from_pretrained(MODEL_NAME,model_max_length=512)
# 
# model = pickle.load(open('/content/drive/MyDrive/t5.pkl', 'rb'))
# 
# def encode_text(text):
#     # Encode the text using the tokenizer
#     encoding = tokenizer.encode_plus(
#         text,
#         max_length=512,
#         padding="max_length",
#         truncation=True,
#         return_attention_mask=True,
#         return_tensors='pt'
#     )
#     return encoding["input_ids"], encoding["attention_mask"]
# 
# def generate_summary(input_ids, attention_mask):
#     # Generate a summary using the best model
#     generated_ids = model.generate(
#         input_ids=input_ids,
#         attention_mask=attention_mask,
#         max_length=150,
#         num_beams=2,
#         repetition_penalty=2.5,
#         length_penalty=1.0,
#         early_stopping=True
#     )
#     return generated_ids
# 
# def decode_summary(generated_ids):
#     # Decode the generated summary
#     summary = [tokenizer.decode(gen_id, skip_special_tokens=True, clean_up_tokenization_spaces=True)
#                for gen_id in generated_ids]
#     return "".join(summary)
# 
# def summarize(text):
#     input_ids, attention_mask = encode_text(text)
#     generated_ids = generate_summary(input_ids, attention_mask)
#     summary = decode_summary(generated_ids)
#     return summary

def encode_text(text):
    # Encode the text using the tokenizer
    encoding = tokenizer.encode_plus(
        text,
        max_length=512,
        padding="max_length",
        truncation=True,
        return_attention_mask=True,
        return_tensors='pt'
    )
    return encoding["input_ids"], encoding["attention_mask"]

def generate_summary(input_ids, attention_mask):
    # Generate a summary using the best model
    generated_ids = model.generate(
        input_ids=input_ids,
        attention_mask=attention_mask,
        max_length=150,
        num_beams=2,
        repetition_penalty=2.5,
        length_penalty=1.0,
        early_stopping=True
    )
    return generated_ids

def decode_summary(generated_ids):
    # Decode the generated summary
    summary = [tokenizer.decode(gen_id, skip_special_tokens=True, clean_up_tokenization_spaces=True)
               for gen_id in generated_ids]
    return "".join(summary)

def summarize(text):
    input_ids, attention_mask = encode_text(text)
    generated_ids = generate_summary(input_ids, attention_mask)
    summary = decode_summary(generated_ids)
    return summary

text="""Several Muslim groups have decided to launch agitations and mount legal challenge to Karnataka BJP government's decision to remove Muslims from the 2B category of Other Backward Classes, which gave them four per cent reservation.

The Karnataka Cabinet, which met on Friday, had also decided to split this quantum of four per cent equally between Vokkaligas and Veerashaiva-Lingayats at two per cent each in jobs and admissions in educational institutions.

The move, which comes ahead of the Assembly elections that are due by May, was welcomed by the two politically influential communities.

The state cabinet also decided that the Muslim community in the state can now avail of benefits under the 10 per cent quota for Economically Weaker Sections (EWS), which is decided based on family income.

Muslim termed it a ''grave injustice meted out to them''.

Some top Muslim religious leaders of Karnataka on Saturday held a meeting where they denounced the move and vowed to fight it out legally. They also called it a political move by the BJP government to win the upcoming Assembly election.

"Today, Muslims are below the SC and ST in terms of education. You can make out from the atrocities being perpetrated against the Muslims," Maulavi Maqsood Imran of Jamia Masjid and a member of the Ulema Council told media.

''We will not hit the street or create ruckus on the road. We will fight for our rights legally.'' he added.

He said there was no objection to Vokkaligas and Lingayats getting additional reservation but it should not happen by taking away someone else's rights.

"We want to appeal to the Vokkaliga and Lingayat seers whether they would like to take those rights which were snatched from others and given to them. We want them to build pressure on the government to get their due share of reservation,'' he said.

According to him, it was possible to enhance the reservation for Vokkaligas and Lingayats without taking it away from Muslims.

In the meeting at the Khadaria Masjid on Millers Road, Muslim religious leaders also consulted lawyers on taking forward the fight legally.

After the Karnataka government decided to increase the reservation for Vokkaligas in 2C category from four per cent to six per cent and Lingayats in 2D category from five per cent to seven per cent, Basava Jaya Mrutyunjaya Swamiji of Panchamasali Peeth ended his two-year old agitation.

He, however, said he had only ''halted'' the agitation till the elections are over and would renew his demands until they are met completely.

According to the Swamiji, the demand was for 15 per cent reservation for Lingayats.

Sri Nirmalanandanatha Swamiji, a key religious leader of the Vokkaliga community, expressed his happiness over the two per cent increase in reservation for the Vokkaligas."""

print(summarize(text))

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import time
# from get_output import summarize
# 
# # Set up Streamlit app
# st.set_page_config(page_title='Text Summarizer')
# st.title('Text Summarizer')
# st.subheader('Developed using T5 transformer and trained on news data.')
# 
# text_input = st.text_input(label='Enter text to summarize')
# 
# if st.button('Summarize'):
#     # Summarize input text
#     if text_input:
#       start = time.time()
#       output = summarize(text_input)
#       endtime = time.time()
#       st.text(f'Total Time taken for Summarizing {endtime-start} seconds')
#       col1, col2 = st.beta_columns(2)
#       with col1:
#           st.subheader('Original Text')
#           st.write(text_input)
#       with col2:
#           st.subheader('Summary')
#           st.write(output)

!npm install localtunnel

!streamlit run /content/app.py &>/content/logs.txt &

!npx localtunnel --port 8501

